<?php
/**
 * @file
 * Include basic hooks for the module functionality.
 */

/**
 * Implements hook_menu().
 */
function ding_webtrekk_menu() {
  $items = [];
  $items['admin/config/ding/webtrekk'] = [
    'title' => 'Webtrekk',
    'description' => 'Settings for the Webtrekk analytics tool.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ding_webtrekk_admin_settings_form'],
    'access arguments' => ['administer site configuration'],
    'file' => 'ding_webtrekk.admin.inc',
  ];

  return $items;
}

/**
 * Implements hook_page_alter().
 */
function ding_webtrekk_page_alter(&$page) {
  $domain = variable_get('webtrekk_ti_domain', '');
  $id = variable_get('webtrekk_ti_id', '');

  if (empty($domain) && empty($id)) {
    return;
  }

  $params = [
    'pageTitle' => drupal_get_title(),
  ];
  _ding_webtrekk_set_data_layer_values($params);

  // @codingStandardsIgnoreStart
  $tag_integration_logic = '/** start TagIntegration loader  */
(function(c,d,a,f){c.wts=c.wts||[];var g=function(b){var a="";b.customDomain&&b.customPath?a=b.customDomain+"/"+b.customPath:b.tiDomain&&b.tiId&&(a=b.tiDomain+"/resp/api/get/"+b.tiId+"?url="+encodeURIComponent(c.location.href)+"&v=5");if(b.option)for(var d in b.option)a+="&"+d+"="+encodeURIComponent(b.option[d]);return a};if(-1===d.cookie.indexOf("wt_r=1")){var e=d.getElementsByTagName(a)[0];a=d.createElement(a);a.async=!0;a.onload=function(){if("undefined"!==typeof c.wt_r&&!isNaN(c.wt_r)){var b=new Date,a=b.getTime()+1E3*parseInt(c.wt_r);b.setTime(a);d.cookie="wt_r=1;path=/;expires="+b.toUTCString()}};a.onerror=function(){"undefined"!==typeof c.wt_mcp_hide&&"function"===typeof c.wt_mcp_hide.show&&(c.wt_mcp_hide.show(),c.wt_mcp_hide.show=function(){})};a.src="//"+g(f);e.parentNode.insertBefore(a,e)}})(window,document,"script",_tiConfig);
/** end TagIntegration loader */';
  // @codingStandardsIgnoreEnd

  $page['page_bottom']['webtrekk']['#attached']['js'] = [
    [
      'data' => 'window._tiConfig = window._tiConfig || {
        tiDomain: ' . "'$domain'," .
        'tiId: ' . "'$id'," .
        'option: {}
      };' . $tag_integration_logic,
      'type' => 'inline',
      'scope' => 'footer',
    ],
  ];

  // Track ting search results. We take advantage of the fact that ting_search
  // module stores the result in a static variable when search is triggered via
  // search_data() function from core search module. Since this is not tied to
  // any path, we also check current_path().
  if (strpos(current_path(), 'search/ting') === 0) {
    if ($search_result = drupal_static('ting_search_results', FALSE)) {
      $params = [
        'pageTitle' => 'Search ting',
        'OSS' => $search_result->search_key,
        'OSSr' => $search_result->numTotalObjects,
      ];
      _ding_webtrekk_set_data_layer_values($params);
    }
  }
}

/**
 * Implements hook_views_post_execute().
 *
 * Track internal search results.
 */
function ding_webtrekk_views_post_execute(&$view) {
  // We also check current_path to ensure we're tracking on the correct page.
  // For example, the view is also executed on ting_search search page to show
  // the number of results to the user, if they searched in content instead.
  // See search_backend.inc ctools content type plugin from ting_search.
  if ($view->name == 'ding_multiple_search' && strpos(current_path(), 'search/node') === 0) {
    // This view is loaded 2 times. Prevent from loading params multiple times.
    $loaded = &drupal_static(__FUNCTION__);
    if (!empty($loaded)) {
      return;
    }
    $loaded = TRUE;

    $params = [
      'internalSearch' => array_shift($view->args),
      'numberSearchResults' => $view->total_rows,
      'pageTitle' => 'Search content',
    ];
    _ding_webtrekk_set_data_layer_values($params);
  }
}

/**
 * Pass Tag Information variables to the inline js script.
 *
 * @param array $value_map
 *   Key, value collection of parameters to be considered.
 */
function _ding_webtrekk_set_data_layer_values(array $value_map) {
  $script_lines = array_map(function($key, $value) {
    if ($value) {
      return "window._ti['$key'] = '$value'";
    }
  }, array_keys($value_map), $value_map);

  // Remove empty values.
  $script_lines = array_filter($script_lines);

  $script_lines = array_merge(
    ['window._ti = window._ti || {}'],
    $script_lines
  );

  $script = implode(";\n", $script_lines);
  drupal_add_js($script, [
    'type' => 'inline',
  ]);
}

/**
 * Implements hook_node_view().
 */
function ding_webtrekk_node_view($node, $view_mode, $langcode) {
  $nid = variable_get('ding2_cookie_page_nid');

  // If this is the cookie page; add the Webtrekk opt-out.
  if ($nid === $node->nid) {
    $text = '<p><strong>Webtrekk</strong></p>
    <p>Vi bruger Webtrekk til at føre statistik over trafikken på hjemmesiden. Al indsamlet statistik er anonym.<br>(<a class="external" href="https://www.webtrekk.com/en/legal/opt-out-webtrekk/">Webtrekk - om brug af cookies på websider og øvrige forhold omkring persondata</a>)<br>- Hvis du vil fravælge cookies fra Webtrekk kan du trykke her:
    <p><a class="button webtrekk-opt-out" href="#">Fravælg Webtrekk cookie</a></p>
    <p>Dette vil sætte en opt-out (følg ikke) cookie i din browser. For at aktivere Webtrekk cookies igen kan du slette den pågældende webtrekkOptOut cookie eller alle cookies i din browseren.</p>
    <p><strong>Hvorfor informerer Biblioteket om cookies?</strong></p><p>Ifølge "Bekendtgørelse om krav til information og samtykke ved lagring af eller adgang til oplysninger i slutbrugerens terminaludstyr" BEK nr 1148 af 09/12/2011 (<a class="external" href="https://www.retsinformation.dk/Forms/R0710.aspx?id=139279">https://www.retsinformation.dk/Forms/R0710.aspx?id=139279</a>) er alle danske hjemmesider forpligtet til at informere om, hvorvidt de anvender cookies. Det sker, så brugeren kan beslutte, om de fortsat ønsker at besøge hjemmesiden, eller om de evt. ønsker at blokere for cookies.</p>';

    $node->content['field_ding_page_body'][0]['#markup'] .= $text;

    drupal_add_js(drupal_get_path('module', 'ding_webtrekk') . '/js/ding_webtrekk.opt-out.js');
  }
}
